[package]
name = "lightports"
version = "0.1.0"
authors = ["Richard"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.6", features = ["std", "winbase", "winuser", "errhandlingapi", "debugapi"] }