SET(CMAKE_SYSTEM_NAME Windows)

# get GCC and G++ if not set
if (NOT CMAKE_CXX_COMPILER)
  find_program(CMAKE_C_COMPILER gcc.exe PATHS ENV PATH NO_DEFAULT_PATH)
  find_program(CMAKE_CXX_COMPILER g++.exe PATHS ENV PATH NO_DEFAULT_PATH)
  find_program(CMAKE_RC_COMPILER windres.exe PATHS ENV PATH NO_DEFAULT_PATH)
endif()
get_filename_component(MSYS2_MINGW_BIN_PATH "${CMAKE_CXX_COMPILER}" DIRECTORY CACHE)
get_filename_component(MSYS2_MINGW_PREFIX "${MSYS2_MINGW_BIN_PATH}" DIRECTORY CACHE)
get_filename_component(MSYS2_PREFIX "${MSYS2_MINGW_BIN_PATH}" DIRECTORY CACHE)
    
# for Find()
SET(CMAKE_FIND_ROOT_PATH "${MSYS2_MINGW_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    
# MSYS2/StaticQt5 specific
set(CMAKE_PREFIX_PATH "${MSYS2_MINGW_PREFIX}/qt5-static")
    
# cleanup vars
unset(MSYS2_MINGW_BIN_PATH)
unset(COMPILER_PREFIX)